/**
 * Created by musta_000 on 7/11/2016.
 */
public class Phages {
//    init.executeUpdate(" CREATE CACHED TABLE Phages( " +
//            " id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
//            " Name VARCHAR(45) NOT NULL, " +
//            " Cluster VARCHAR(45) NOT NULL, " +
//            " Strain VARCHAR(45) NOT NULL, " +
//            " PRIMARY KEY (id)) ");
    private String Name;
    private String Cluster;
    private String Strain;

    public String getName() {
        return Name;
    }

    public void setName(String name) {
        Name = name;
    }

    public String getCluster() {
        return Cluster;
    }

    public void setCluster(String cluster) {
        Cluster = cluster;
    }

    public String getStrain() {
        return Strain;
    }

    public void setStrain(String strain) {
        Strain = strain;
    }

    @Override
    public String toString() {
        return "Phages{" +
                "Name='" + Name + '\'' +
                ", Cluster='" + Cluster + '\'' +
                ", Strain='" + Strain + '\'' +
                '}';
    }
    public void clear(){
        Name="";
        Cluster="";
        Strain="";
    }
}
