/**
 * Created by musta_000 on 7/11/2016.
 */
public class Primers {
//    String x =" id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
//            " Sequence BIGINT NOT NULL, " +
//            " Strain VARCHAR(45) NOT NULL, " +
//            " Cluster VARCHAR(45) NOT NULL, " +
//            " Hairpin BOOLEAN NULL, "+
//            " PRIMARY KEY (id)) ";
    private long Sequence;
    private String Strain;
    private String Cluster;
    private boolean Hairpin;

    public long getSequence() {
        return Sequence;
    }

    public void setSequence(long sequence) {
        Sequence = sequence;
    }

    public String getStrain() {
        return Strain;
    }

    public void setStrain(String strain) {
        Strain = strain;
    }

    public String getCluster() {
        return Cluster;
    }

    public void setCluster(String cluster) {
        Cluster = cluster;
    }

    public boolean isHairpin() {
        return Hairpin;
    }

    public void setHairpin(boolean hairpin) {
        Hairpin = hairpin;
    }

    @Override
    public String toString() {
        return "Primers{" +
                "Sequence=" + Sequence +
                ", Strain='" + Strain + '\'' +
                ", Cluster='" + Cluster + '\'' +
                ", Hairpin=" + Hairpin +
                '}';
    }
    public void clear() {
        Sequence=0L;
        Strain="";
        Cluster="";
        Hairpin=false;
    }

}
