/**
 * Created by musta_000 on 7/11/2016.
 */
public class Primers {
//    String x =" id INTEGER GENERATED BY DEFAULT AS IDENTITY, " +
//            " Sequence BIGINT NOT NULL, " +
//            " pStrain VARCHAR(45) NOT NULL, " +
//            " pCluster VARCHAR(45) NOT NULL, " +
//            " Hairpin BOOLEAN NULL, "+
//            " PRIMARY KEY (id)) ";
//    private long timestamp;
    private long Sequence;
    private String Strain;
    private String Cluster;
    private boolean Hairpin;

    public long getSequence() {
        return Sequence;
    }

    public void setSequence(long sequence) {
        Sequence = sequence;
    }

    public String getStrain() {
        return Strain;
    }

    public void setStrain(String strain) {
        Strain = strain;
    }

    public String getCluster() {
        return Cluster;
    }

    public void setCluster(String cluster) {
        Cluster = cluster;
    }

    public boolean isHairpin() {
        return Hairpin;
    }

    public void setHairpin(boolean hairpin) {
        Hairpin = hairpin;
    }

//    public long getTimestamp() {
//        return timestamp;
//    }

//    public void setTimestamp(long timestamp) {
//        this.timestamp = timestamp;
//    }

    @Override
    public String toString() {
        return "Primers{" +
                "Sequence=" + Sequence +
                ", pStrain='" + Strain + '\'' +
                ", pCluster='" + Cluster + '\'' +
                ", Hairpin=" + Hairpin +
                '}';
    }
    @Override
    public int hashCode() {
        int result;
        result =  (int) (Sequence ^ (Sequence >>> 32));
//        result = (int) (timestamp ^ (timestamp >>> 32));
        result = 31 * result + (Cluster != null ? Cluster.hashCode() : 0);
        result = 31 * result + (Strain != null ? Strain.hashCode() : 0);
        return result;
    }
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Primers)) return false;

        Primers q = (Primers) o;

        return Sequence == q.Sequence
//                && timestamp == q.timestamp
                && !(Strain != null ? !Strain.equals(q.Strain) : q.Strain != null)
                && !(Cluster != null ? !Cluster.equals(q.Cluster) : q.Cluster != null);

    }
    public void clear() {
        Sequence=0L;
//        timestamp=0L;
        Strain=null;
        Cluster=null;
        Hairpin=false;
    }

}
